notifications:
  email: false
git:
  quiet: true
  depth: false
env:
  global:
  - TERM=dumb
language: java
services: docker
addons:
  apt:
    update: true
    packages:
    - bash
    - curl
    - python3
    - python3-pip
install: true
before_install:
- mkdir -p $HOME/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- $(which pip3) install --user $(whoami) --upgrade pip
- $(which pip3) install --user $(whoami) --upgrade httpie
#- $(which pip3) install --user $(whoami) --upgrade httpie docker-compose
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
- stop_any 8080 80
jobs:
  include:
  - stage: test
    jdk: openjdk8
    name: jdk8
    script: cd $TRAVIS_BUILD_DIR && ./mvnw
#  - stage: test
#    jdk: openjdk11
#    name: jdk11
#    script: cd $TRAVIS_BUILD_DIR && ./mvnw
#  - stage: test
#    jdk: openjdk8
#    name: test
#    script:
#    - cd $TRAVIS_BUILD_DIR && ./mvnw
#    - cd java -jar $TRAVIS_BUILD_DIR/hazelcast/target/*-all.jar
  - stage: test
    jdk: openjdk11
    name: test
    script:
    - cd $TRAVIS_BUILD_DIR && ./mvnw -DskipTests >/dev/null
    - java -jar $TRAVIS_BUILD_DIR/hazelcast/target/*-all.jar
  - stage: test
    jdk: openjdk8
    name: display-property-updates
    script:
#    - cd $TRAVIS_BUILD_DIR && ./mvnw versions:display-parent-updates versions:display-plugin-updates versions:display-dependency-updates -U >/dev/null
#    - cd $TRAVIS_BUILD_DIR && ./mvnw versions:display-plugin-updates versions:display-parent-updates versions:display-dependency-updates
    - cd $TRAVIS_BUILD_DIR && ./mvnw versions:display-dependency-updates -U >/dev/null
    - cd $TRAVIS_BUILD_DIR && ./mvnw versions:display-dependency-updates
#  - stage: test
#    jdk: openjdk11
#    name: display-property-updates jdk11
#    script:
#    - cd $TRAVIS_BUILD_DIR && ./mvnw versions:display-parent-updates versions:display-plugin-updates versions:display-dependency-updates -U >/dev/null
#    - cd $TRAVIS_BUILD_DIR && ./mvnw versions:display-parent-updates versions:display-plugin-updates versions:display-dependency-updates
cache:
  pip: true
  packages: true
  directories:
  - ~/.docker/
  - ~/.m2/
